name: mi_card
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - image/potato.jpg

  fonts:
    - family: Anton
      fonts:
        - asset: font/Anton-Regular _copy.ttf
    - family: tiny5
      fonts:
        - asset: font/Tiny5-Regular_copy.ttf
    - family: Montserrat
      fonts:
        - asset: font/Montserrat-VariableFont_wght _copy